### ISSUE TITLE
OSError: libspatialindex_c.so.5: cannot open shared object file

### ISSUE THREAD

**Issue by n1try** [motion-planning/rrt-algorithms#24]
I'm getting the following error. Any ideas?

```
Traceback (most recent call last):
  File "examples/rrt/rrt_2d.py", line 5, in <module>
    from src.rrt.rrt import RRT
  File "/home/ferdinand/dev/rrt-algorithms/src/rrt/rrt.py", line 1, in <module>
    from src.rrt.rrt_base import RRTBase
  File "/home/ferdinand/dev/rrt-algorithms/src/rrt/rrt_base.py", line 5, in <module>
    from src.rrt.tree import Tree
  File "/home/ferdinand/dev/rrt-algorithms/src/rrt/tree.py", line 1, in <module>
    from rtree import index
  File "/home/ferdinand/.local/lib/python3.6/site-packages/rtree/__init__.py", line 1, in <module>
    from .index import Rtree
  File "/home/ferdinand/.local/lib/python3.6/site-packages/rtree/index.py", line 5, in <module>
    from . import core
  File "/home/ferdinand/.local/lib/python3.6/site-packages/rtree/core.py", line 127, in <module>
    rt = ctypes.CDLL(lib_name)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libspatialindex_c.so.5: cannot open shared object file: No such file or directory
```

**Comment by SZanlongo** [comment]
That seems like an issue with the python environment. Try printing `os.environ` right before the exception to see if it has the correct environment. It could be that the rtree library isn't being correctly detected. You could try rebooting or doing `sudo ldconfig` on linux.

**Comment by n1try** [comment]
[This](https://github.com/Toblerity/rtree/issues/56#issuecomment-339100783) helped.
